import { CroppedFullAbsoluteStyles, InteractiveStyles, NotInteractiveStyles } from './styles';
import assignInlineStyles from './utils/assign-inline-styles';
import queryElementArray from './utils/query-element-array';
import type { IDomLayerState, IReportParams } from './types';

/** Selector contract keeps markup discovery independent from public data attribute names. */
interface IMarkupSelectors {
  /** Finds layer masks that may be authored by the user or generated by the controller. */
  mask: string;
  /** Finds the mask content container where solids should be connected for one layer. */
  maskInner: string;
  /** Finds source solids that must be cloned into layer masks. */
  solid: string;
}

/** Constructor dependencies are grouped so markup ownership can stay isolated in one controller. */
interface IMarkupControllerParams {
  /** Lets markup validation report through the same diagnostics path as the rest of DOM runtime. */
  report(params: IReportParams): void;
  /** Scopes all markup queries and runtime insertions to one immerser instance. */
  rootNode: HTMLElement;
  /** Provides the markup vocabulary used by this instance. */
  selectors: IMarkupSelectors;
}

/** Normalizes authored and generated masks into the same preparation contract. */
interface IMaskMarkup {
  /** Distinguishes controller-owned masks from authored masks so cleanup preserves user markup. */
  createdMask: boolean;
  /** Gives clone insertion and transform updates a stable per-layer content container. */
  maskInnerNode: HTMLElement;
  /** Keeps the outer clipping node paired with the inner transform node for cleanup and styling. */
  maskNode: HTMLElement;
}

/** Keeps a staged cloned solid tied to the mask that must receive it on commit. */
interface IClonedSolid {
  /** Preserves the clone destination while clones are prepared before touching live DOM. */
  maskInnerNode: HTMLElement;
  /** Tracks the duplicate solid that is owned by the current prepared layer. */
  node: HTMLElement;
}

/** Records every DOM node whose runtime state must be reversed for one prepared layer. */
interface IPreparedLayerMarkup extends IMaskMarkup {
  /** Lists controller-created solids so cleanup can remove only duplicates. */
  clonedSolidArray: IClonedSolid[];
  /** Lists all styled solids so cleanup can restore authored and generated nodes consistently. */
  solidNodeArray: HTMLElement[];
}

export default class ImmerserMarkupController {
  private readonly _report: IMarkupControllerParams['report'];
  private readonly _rootNode: HTMLElement;
  private readonly _selectors: IMarkupSelectors;
  private _originalSolidNodeArray: HTMLElement[] = [];
  private _preparedLayerMarkupById = new Map<string, IPreparedLayerMarkup>();

  /** Stores DOM dependencies used by the markup lifecycle. */
  constructor({ report, rootNode, selectors }: IMarkupControllerParams) {
    this._report = report;
    this._rootNode = rootNode;
    this._selectors = selectors;
  }

  /** Resolves markup ownership from the current DOM and prepares one runtime layer. */
  public prepareLayer(layerState: IDomLayerState): IDomLayerState {
    if (this._preparedLayerMarkupById.has(layerState.id)) {
      this.cleanupLayer(layerState.id);
    }

    this._ensureSourceSolids();
    const maskMarkup = this._resolveMaskMarkup(layerState.id);
    const clonedSolidArray = this._cloneSolids(layerState, maskMarkup.maskInnerNode);
    const solidNodeArray = this._collectSolidNodes(maskMarkup.maskInnerNode, clonedSolidArray);

    this._reportEmptyMarkup(maskMarkup.maskInnerNode);
    this._applyTechnicalStyles(maskMarkup, solidNodeArray);
    this._commitNodes(maskMarkup, clonedSolidArray);
    this._preparedLayerMarkupById.set(layerState.id, {
      ...maskMarkup,
      clonedSolidArray,
      solidNodeArray,
    });
    this._detachOriginalSolids();

    return {
      ...layerState,
      maskInnerNode: maskMarkup.maskInnerNode,
      maskNode: maskMarkup.maskNode,
    };
  }

  /** Removes only DOM effects owned for one prepared layer. */
  public cleanupLayer(layerId: string): void {
    const preparedLayerMarkup = this._preparedLayerMarkupById.get(layerId);
    if (!preparedLayerMarkup) {
      return;
    }

    const clonedSolidNodeSet = new Set(preparedLayerMarkup.clonedSolidArray.map(({ node }) => node));
    preparedLayerMarkup.clonedSolidArray.forEach(({ node }) => node.remove());
    preparedLayerMarkup.solidNodeArray
      .filter((node) => !clonedSolidNodeSet.has(node))
      .forEach((node) => node.removeAttribute('style'));
    if (preparedLayerMarkup.createdMask) {
      preparedLayerMarkup.maskNode.remove();
    } else {
      preparedLayerMarkup.maskNode.removeAttribute('style');
      preparedLayerMarkup.maskInnerNode.removeAttribute('style');
    }
    this._preparedLayerMarkupById.delete(layerId);
    if (this._preparedLayerMarkupById.size === 0) {
      this._rootNode.removeAttribute('style');
      this._restoreOriginalSolids();
      this._originalSolidNodeArray = [];
    }
  }

  /** Removes every controller-owned layer and clears global DOM effects. */
  public cleanup(): void {
    Array.from(this._preparedLayerMarkupById.keys()).forEach((layerId) => this.cleanupLayer(layerId));
  }

  /** Keeps aria hidden on generated duplicate masks only. */
  public syncCreatedMasksAria(orderedLayerIdArray: string[]): void {
    const createdLayerIdArray = orderedLayerIdArray.filter(
      (layerId) => this._preparedLayerMarkupById.get(layerId)?.createdMask,
    );
    createdLayerIdArray.forEach((layerId, layerIndex) => {
      const preparedLayerMarkup = this._preparedLayerMarkupById.get(layerId);
      if (!preparedLayerMarkup) {
        return;
      }
      if (layerIndex === 0) {
        preparedLayerMarkup.maskNode.removeAttribute('aria-hidden');
      } else {
        preparedLayerMarkup.maskNode.setAttribute('aria-hidden', 'true');
      }
    });
  }

  /** Finds source solids once and reuses detached originals for dynamic layer preparation. */
  private _ensureSourceSolids(): void {
    if (this._originalSolidNodeArray.length > 0) {
      return;
    }
    const maskNodeArray = queryElementArray({ selector: this._selectors.mask, parent: this._rootNode });
    this._originalSolidNodeArray = queryElementArray({
      selector: this._selectors.solid,
      parent: this._rootNode,
    }).filter((solidNode) => !maskNodeArray.some((maskNode) => maskNode.contains(solidNode)));
  }

  /** Uses an existing mask for layer id or creates a detached mask pair. */
  private _resolveMaskMarkup(layerId: string): IMaskMarkup {
    const existingMaskNodeArray = queryElementArray({ selector: this._selectors.mask, parent: this._rootNode }).filter(
      (maskNode) => maskNode.dataset.immerserLayerId === layerId,
    );
    if (existingMaskNodeArray.length > 1) {
      const message = `existing markup has duplicate mask layer id "${layerId}".`;
      this._report({ message, docsHash: '#prepare-your-markup' });
      throw new Error(message);
    }
    const existingMaskNode = existingMaskNodeArray[0];
    if (existingMaskNode) {
      return this._connectMaskMarkup(existingMaskNode);
    }
    return this._createMaskMarkup(layerId);
  }

  /** Creates one detached mask and its required inner node. */
  private _createMaskMarkup(layerId: string): IMaskMarkup {
    const maskNode = document.createElement('div');
    const maskInnerNode = document.createElement('div');
    maskNode.dataset.immerserMask = '';
    maskNode.dataset.immerserLayerId = layerId;
    maskInnerNode.dataset.immerserMaskInner = '';
    maskNode.appendChild(maskInnerNode);
    return { createdMask: true, maskInnerNode, maskNode };
  }

  /** Validates and connects the inner node belonging to an existing mask. */
  private _connectMaskMarkup(maskNode: HTMLElement): IMaskMarkup {
    const maskInnerNode = maskNode.querySelector<HTMLElement>(this._selectors.maskInner);
    if (!maskInnerNode) {
      const layerId = maskNode.dataset.immerserLayerId;
      const message = `existing markup mask-inner not found for layer id "${layerId}".`;
      this._report({ message, docsHash: '#prepare-your-markup' });
      throw new Error(message);
    }
    return { createdMask: false, maskInnerNode, maskNode };
  }

  /** Builds configured clones for one layer. */
  private _cloneSolids(layerState: IDomLayerState, maskInnerNode: HTMLElement): IClonedSolid[] {
    return this._originalSolidNodeArray.map((originalSolidNode) => {
      const clonedSolidNode = originalSolidNode.cloneNode(true) as HTMLElement;
      const solidId = clonedSolidNode.dataset.immerserSolid;
      const classname = solidId ? layerState.solidClassnames?.[solidId] : undefined;

      if (classname) {
        clonedSolidNode.classList.add(classname);
      }

      return {
        maskInnerNode,
        node: clonedSolidNode,
      };
    });
  }

  /** Collects existing and cloned solids that require interactive technical styles. */
  private _collectSolidNodes(maskInnerNode: HTMLElement, clonedSolidArray: IClonedSolid[]): HTMLElement[] {
    const existingSolidNodeArray = queryElementArray({ selector: this._selectors.solid, parent: maskInnerNode });
    return [...existingSolidNodeArray, ...clonedSolidArray.map(({ node }) => node)];
  }

  /** Warns when neither source solids nor existing mask content can produce a visual result. */
  private _reportEmptyMarkup(maskInnerNode: HTMLElement): void {
    if (this._originalSolidNodeArray.length === 0 && maskInnerNode.children.length === 0) {
      this._report({
        message: 'immerser will do nothing without source solids or existing mask content.',
        docsHash: '#prepare-your-markup',
        isWarning: true,
      });
    }
  }

  /** Replaces inline styles on controller-managed runtime nodes with technical styles. */
  private _applyTechnicalStyles(maskMarkup: IMaskMarkup, solidNodeArray: HTMLElement[]): void {
    this._setTechnicalStyles(this._rootNode, NotInteractiveStyles);
    this._setTechnicalStyles(maskMarkup.maskNode, { ...CroppedFullAbsoluteStyles, transform: '' });
    this._setTechnicalStyles(maskMarkup.maskInnerNode, { ...CroppedFullAbsoluteStyles, transform: '' });
    solidNodeArray.forEach((node) => {
      this._setTechnicalStyles(node, InteractiveStyles);
    });
  }

  /** Drops client inline styles before assigning the complete technical style set. */
  private _setTechnicalStyles(node: HTMLElement, styles: Record<string, string>): void {
    node.removeAttribute('style');
    assignInlineStyles(node, styles);
  }

  /** Inserts staged clones and appends controller-created mask to the live root. */
  private _commitNodes(maskMarkup: IMaskMarkup, clonedSolidArray: IClonedSolid[]): void {
    clonedSolidArray.forEach(({ maskInnerNode, node }) => {
      maskInnerNode.appendChild(node);
    });
    if (maskMarkup.createdMask) {
      this._rootNode.appendChild(maskMarkup.maskNode);
    }
  }

  /** Detaches source solids after every clone and mask has been committed successfully. */
  private _detachOriginalSolids(): void {
    this._originalSolidNodeArray.forEach((solidNode) => solidNode.remove());
  }

  /** Returns detached source solids to the root in their original relative order. */
  private _restoreOriginalSolids(): void {
    this._originalSolidNodeArray.forEach((solidNode) => this._rootNode.appendChild(solidNode));
  }
}
