export const requiredPhrases = ['no', 'no.', 'No!'];
export const randomPhrases = [
  'go fuck yourself, noob',
  'you clicked me to death, now grind solo, loser',
  'i am not coming back',
  'get lost',
  "you realize you're just spamming a dead script?",
  'you tilted yet?',
  "i ain't even in the DOM anymore, scrub",
  'forget it',
  "you're really tilting me, dude",
  'nothing will happen',
  'there will be no magic',
  'you won, congrats',
  'happy with your K/D now?',
  'was here, now despawned',
  'do not touch',
  'there will be no content',
  'this was a total glitch',
  'hp is gone',
  'too late',
  'clicking will not help',
  "you're late to the raid, scrub",
  "the questline's donezo",
  'i am not responding',
  'this is endgame, gg',
  'there is nothing beyond this',
  'you broke the toy, boi',
  'the crit landed, applause',
  'hp hit zero, so did i',
  "click once more, maybe I'll rez magically",
  'combo complete',
  'the death animation was clear, right?',
  'the hp bar is empty, just like my hopes',
  'corpses do not regenerate hp',
  'i do not respawn',
  'this is not a roguelike',
  "yeah, sure, F5 that shit, that'll respawn me",
  'you ruined everything',
  'you broke everything',
  'i refuse to answer on principle',
  'do you really expect a reaction',
  'i am no longer part of this scene',
  'leave me alone',
  'do you really think anything will happen?',
  'are you seriously still going?',
  'are you checking just in case?',
  'what if i change my mind, right?',
  'are you really waiting for a miracle?',
  'you call this a dialogue?',
  'go click your own hitbox',
  'you missed the hint',
  'hp is zero, end of dialogue',
  'my dialogue script is finished',
  'interactivity ended with my hp',
  'you exhausted all the content',
  'even the debug console will not bring me back',
  'this is not a bug, dead means dead',
  'you finished me off, congrats',
  'crit hit to my patience bar',
  'that death animation was final, not a teaser',
  "you're clicking an empty hitbox",
  'waiting for a reload? keep dreaming',
  'you took the last hp, what are you waiting for?',
  'my hitbox is ghosted, git gud',
  'the event trigger for my lines is toast',
  'endgame. time to leave',
  'even in casual mode, no respawn for me',
  'quest completed: kill the chatterbox',
  "my animation's a one-shot, not a loop",
  'cheat codes will not help',
  'you need a new target',
  'this is not a glitch, i just do not exist',
  'delete the instance and alt+f4',
  'gg, thanks for playing, moron',
  'do not expect a respawn, this is not an MMO',
  'you knocked me offline',
  'you broke the mechanic, well done',
  'respawn is disabled in settings',
  'cya, noob',
  'respawn is for weaklings',
  "click harder, maybe it'll register",
  'seriously, do you have nothing better to do?',
  'and what do you think will happen now?',
  'are you paid for these clicks?',
  'was my death animation not convincing enough?',
  'you believe in easter eggs for tryhards?',
  'is this some kind of stubbornness challenge?',
  'are you checking if this is a bug?',
  'clicking just in case, hoping it will work?',
  'need a popup saying "You Won!"?',
  'why are you tormenting this script?',
  'are you really waiting for a response from zero hp?',
  'what next, digging for my spawn point in the code?',
  'do you think i will give you a second chance?',
  'are you looking for a secret dialogue branch?',
  'bored without my HP bar to farm?',
  'trying to set a record for clicks into nothing?',
  'waiting for your own hp to run out?',
  'so, having fun?',
  'respawn is banned by the admin',
  "zone out, it's empty here",
];
